// Code generated by goadlc v3 - DO NOT EDIT.
package gotypes

import (
	"github.com/adl-lang/goadlc/internal/cli/gomod"
	"github.com/adl-lang/goadlc/internal/cli/loader"
	"github.com/adl-lang/goadlc/internal/cli/root"
)

type GoTypes struct {
	_GoTypes
}

type _GoTypes struct {
	Root       *root.Root      `json:"-"`
	Loader     *loader.Loader  `json:"-"`
	GoMod      *gomod.GoModule `json:"-"`
	ChangePWD  string          `json:"ChangePWD"`
	NoGoFmt    bool            `json:"NoGoFmt"`
	GoAdlPath  string          `json:"GoAdlPath"`
	ExcludeAst bool            `json:"ExcludeAst"`
	StdLibGen  bool            `json:"StdLibGen"`
	Outputdir  string          `json:"Outputdir"`
}

func MakeAll_GoTypes(
	root *root.Root,
	loader *loader.Loader,
	gomod *gomod.GoModule,
	changepwd string,
	nogofmt bool,
	goadlpath string,
	excludeast bool,
	stdlibgen bool,
	outputdir string,
) GoTypes {
	return GoTypes{
		_GoTypes{
			Root:       root,
			Loader:     loader,
			GoMod:      gomod,
			ChangePWD:  changepwd,
			NoGoFmt:    nogofmt,
			GoAdlPath:  goadlpath,
			ExcludeAst: excludeast,
			StdLibGen:  stdlibgen,
			Outputdir:  outputdir,
		},
	}
}

func Make_GoTypes(
	outputdir string,
) GoTypes {
	ret := GoTypes{
		_GoTypes{
			Root:       ((*GoTypes)(nil)).Default_Root(),
			Loader:     ((*GoTypes)(nil)).Default_Loader(),
			GoMod:      ((*GoTypes)(nil)).Default_GoMod(),
			ChangePWD:  ((*GoTypes)(nil)).Default_ChangePWD(),
			NoGoFmt:    ((*GoTypes)(nil)).Default_NoGoFmt(),
			GoAdlPath:  ((*GoTypes)(nil)).Default_GoAdlPath(),
			ExcludeAst: ((*GoTypes)(nil)).Default_ExcludeAst(),
			StdLibGen:  ((*GoTypes)(nil)).Default_StdLibGen(),
			Outputdir:  outputdir,
		},
	}
	return ret
}

func (*GoTypes) Default_Root() *root.Root {
	return nil
}
func (*GoTypes) Default_Loader() *loader.Loader {
	return nil
}
func (*GoTypes) Default_GoMod() *gomod.GoModule {
	return nil
}
func (*GoTypes) Default_ChangePWD() string {
	return ""
}
func (*GoTypes) Default_NoGoFmt() bool {
	return false
}
func (*GoTypes) Default_GoAdlPath() string {
	return "github.com/adl-lang/goadl_rt/v3"
}
func (*GoTypes) Default_ExcludeAst() bool {
	return false
}
func (*GoTypes) Default_StdLibGen() bool {
	return false
}
