// Code generated by goadlc v3 - DO NOT EDIT.
package root

import ()

type Root struct {
	_Root
}

type _Root struct {
	Debug      bool   `json:"Debug"`
	Cfg        string `json:"Cfg"`
	DumpConfig bool   `json:"DumpConfig"`
}

func MakeAll_Root(
	debug bool,
	cfg string,
	dumpconfig bool,
) Root {
	return Root{
		_Root{
			Debug:      debug,
			Cfg:        cfg,
			DumpConfig: dumpconfig,
		},
	}
}

func Make_Root() Root {
	ret := Root{
		_Root{
			Debug:      ((*Root)(nil)).Default_Debug(),
			Cfg:        ((*Root)(nil)).Default_Cfg(),
			DumpConfig: ((*Root)(nil)).Default_DumpConfig(),
		},
	}
	return ret
}

func (*Root) Default_Debug() bool {
	return false
}
func (*Root) Default_Cfg() string {
	return ""
}
func (*Root) Default_DumpConfig() bool {
	return false
}
