// Code generated by goadlc v3 - DO NOT EDIT.
package gengo

import (
	"github.com/adl-lang/goadlc/internal/cli/goapi"
	"github.com/adl-lang/goadlc/internal/cli/gomod"
	"github.com/adl-lang/goadlc/internal/cli/gotypes"
	"github.com/adl-lang/goadlc/internal/cli/loader"
	"github.com/adl-lang/goadlc/internal/cli/root"
)

type GenGo struct {
	_GenGo
}

type _GenGo struct {
	Root      *root.Root       `json:"-"`
	Loader    *loader.Loader   `json:"Loader"`
	Mod       *gomod.GoModule  `json:"Mod"`
	ChangePWD string           `json:"ChangePWD"`
	GoTypes   *gotypes.GoTypes `json:"GoTypes"`
	GoApis    *[]goapi.GoApi   `json:"GoApis"`
}

func MakeAll_GenGo(
	root *root.Root,
	loader *loader.Loader,
	mod *gomod.GoModule,
	changepwd string,
	gotypes *gotypes.GoTypes,
	goapis *[]goapi.GoApi,
) GenGo {
	return GenGo{
		_GenGo{
			Root:      root,
			Loader:    loader,
			Mod:       mod,
			ChangePWD: changepwd,
			GoTypes:   gotypes,
			GoApis:    goapis,
		},
	}
}

func Make_GenGo(
	loader *loader.Loader,
	mod *gomod.GoModule,
	gotypes *gotypes.GoTypes,
) GenGo {
	ret := GenGo{
		_GenGo{
			Root:      ((*GenGo)(nil)).Default_root(),
			Loader:    loader,
			Mod:       mod,
			ChangePWD: ((*GenGo)(nil)).Default_ChangePWD(),
			GoTypes:   gotypes,
			GoApis:    ((*GenGo)(nil)).Default_GoApis(),
		},
	}
	return ret
}

func (*GenGo) Default_root() *root.Root {
	return nil
}
func (*GenGo) Default_ChangePWD() string {
	return ""
}
func (*GenGo) Default_GoApis() *[]goapi.GoApi {
	return nil
}
